set_property IOSTANDARD LVCMOS18 [get_ports {ja[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ja[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ja[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ja[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ja[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ja[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ja[7]}]

set_property PACKAGE_PIN W19 [get_ports {ja[7]}]
set_property PACKAGE_PIN W18 [get_ports {ja[6]}]
set_property PACKAGE_PIN U19 [get_ports {ja[5]}]
set_property PACKAGE_PIN U18 [get_ports {ja[4]}]
set_property PACKAGE_PIN Y17 [get_ports {ja[3]}]
set_property PACKAGE_PIN Y16 [get_ports {ja[2]}]
set_property PACKAGE_PIN Y19 [get_ports {ja[1]}]

set_property IOSTANDARD LVCMOS18 [get_ports {jb[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {jb[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {jb[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {jb[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {jb[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {jb[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {jb[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {jb[6]}]

set_property PACKAGE_PIN W13 [get_ports {jb[7]}]
set_property PACKAGE_PIN V12 [get_ports {jb[6]}]
set_property PACKAGE_PIN W16 [get_ports {jb[5]}]
set_property PACKAGE_PIN V16 [get_ports {jb[4]}]
set_property PACKAGE_PIN T10 [get_ports {jb[3]}]
set_property PACKAGE_PIN T11 [get_ports {jb[2]}]
set_property PACKAGE_PIN Y14 [get_ports {jb[1]}]
set_property PACKAGE_PIN W14 [get_ports {jb[0]}]



create_clock -period 8.000 -name sys_clk_pin -waveform {0.000 4.000} -add [get_ports clk]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS18} [get_ports clk]

set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS18} [get_ports led0_r]
set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS18} [get_ports led1_r]
set_property -dict {PACKAGE_PIN D20 IOSTANDARD LVCMOS18} [get_ports {btn[0]}]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS18} [get_ports {btn[1]}]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS18} [get_ports {ja[0]}]

set_property MARK_DEBUG true [get_nets tl/spi_serial_ctrl_ready]
set_property MARK_DEBUG true [get_nets tl/ttl_serial_ctrl_ready]
set_property MARK_DEBUG true [get_nets tl/oTx]
set_property MARK_DEBUG true [get_nets tl/oSCK]
set_property MARK_DEBUG true [get_nets tl/iClk]

# Following lines iplement the logic analyzer

#create_debug_core u_ila_0 ila
#set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
#set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
#set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
#set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
#set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
#set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
#set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
#set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
#set_property port_width 1 [get_debug_ports u_ila_0/clk]
#connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
#set_property port_width 1 [get_debug_ports u_ila_0/probe0]
#connect_debug_port u_ila_0/probe0 [get_nets [list tl/iClk]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
#set_property port_width 1 [get_debug_ports u_ila_0/probe1]
#connect_debug_port u_ila_0/probe1 [get_nets [list tl/oPulse]]
#create_debug_port u_ila_0 probe
#set_property port_width 1 [get_debug_ports u_ila_0/probe2]
#connect_debug_port u_ila_0/probe2 [get_nets [list tl/oSCK]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
#set_property port_width 1 [get_debug_ports u_ila_0/probe3]
#connect_debug_port u_ila_0/probe3 [get_nets [list tl/oTx]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
#set_property port_width 1 [get_debug_ports u_ila_0/probe4]
#connect_debug_port u_ila_0/probe4 [get_nets [list tl/spi_serial_ctrl_ready]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
#set_property port_width 1 [get_debug_ports u_ila_0/probe5]
#connect_debug_port u_ila_0/probe5 [get_nets [list tl/ttl_serial_ctrl_ready]]
#set_property MARK_DEBUG true [get_nets tl/oMOSI]
#set_property MARK_DEBUG true [get_nets tl/oSS]
#set_property MARK_DEBUG true [get_nets tl/spi_serial_ctrl_trigger]
#set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
#set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
#set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
#connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
